### ISSUE TITLE
Changing ValidatedIdentifier namespaces

### ISSUE THREAD

**Issue by MincraftEinstein** [fzzyhmstrs/fconfig#22]
This is more of a suggestion than a bug.
When trying to use a different namespace in a ValidatedIdentifier, I (and I think most people) would delete the existing value including the namespace, and start typing the new namespace and value. The issue is that when typing, the default Minecraft namespace gets inserted in front of all existing text. This is a helpful feature if the value always needs to be prepended with the default namespace, but if you want to change the namespace this gets kind of annoying because the only way I have found to be able to change it is by typing out the new namespace and value, and then deleting the prepended `minecraft:`

**Comment by fzzyhmstrs** [comment]
I'm not entirely sure the circumstances you are referring to. I can delete an identifier and type one in with a new namespace no problem, as shown in the example video

https://github.com/user-attachments/assets/1544cf8a-1f2e-4200-9596-98141929dd07

**Comment by MincraftEinstein** [comment]
It must be only when using an unvalidated ValidatedIdenifier I guess. Probably should have done this in the first place rather than trying to explain it.

https://github.com/user-attachments/assets/21b4e034-227f-4698-b13f-8a2827c9c63c
` public ValidatedIdentifier testConfig = new ValidatedIdentifier(ResourceLocation.withDefaultNamespace("test_value"));`

**Comment by fzzyhmstrs** [comment]
I see.. interesting behavior, I will look into it.

Regarding this specific use case, I believe that the screen should already be restricting out-of-game access to that setting, unless it is specifically @NonSync or @ClientModifiable in your case. 

If it is being restricted, using the Biome registry key in the ofRegistryKey method is likely a good option since it can only be modified in-game already. If it isn't being restricted (and it's not Nonsync/Clientmodifiable), that is a bug and I'd like to know about it.

**Comment by MincraftEinstein** [comment]
I'm using it as a client side only config so there isn't any syncing and or disabling outside of worlds, its just a validated identifier, nothing special.

**Comment by fzzyhmstrs** [comment]
in dev, validated identifiers created based on dynamic registry keys will lock themselves when out of game

Also in dev have a fix for the identifier text box autofill
