### ISSUE TITLE
[Bug] I can't access the SubtleEffects mod's config in 1.20.1, fabric version

### ISSUE THREAD

**Issue by Greg727** [fzzyhmstrs/fconfig#23]
I told SubtleEffects' developers the same thing, they said it was a bug with Fzzy Config, can you please fix it?

**Comment by fzzyhmstrs** [comment]
I can't do anything without any details. Can't access? Where? In game? Main menu? With command or with modmenu?

**Comment by fzzyhmstrs** [comment]
I don't see that subtle effects is in that instance at all:
![image](https://github.com/user-attachments/assets/315a985f-7a85-4491-bcd3-1860fa9d6ef4)
![Screenshot 2024-11-08 154848](https://github.com/user-attachments/assets/69ae37e6-2dc1-428a-a771-e251a79fc05d)

**Comment by fzzyhmstrs** [comment]
adding the mod to my own test instance, and what I see is that I can't access the config via modmenu, but via the command `\configure subtle_effects` it works just fine. This appears to be because the init() method of their configs class isn't actually called, so the configs aren't available when modmenu is asking for config screens
![image](https://github.com/user-attachments/assets/c6a77906-0653-4893-9d04-fdd591792611)
