### ISSUE TITLE
[Feature request] Support for Luckperms and/or other permissions plugins in the annotations

### ISSUE THREAD

**Issue by Nindouja** [fzzyhmstrs/fconfig#4]
It would be a great addition to manage permissions not only with vanilla permissions system but a more robust one as well.

We could have a `@WithLuckPerms` similar to `@WithPerms` that will assume luckperms is avaiable on the classpath and then; checkin [ConfigScreenManager](https://github.com/fzzyhmstrs/fconfig/blob/8a9dfb70f680062f67980785c38683d874839146/src/main/kotlin/me/fzzyhmstrs/fzzy_config/screen/internal/ConfigScreenManager.kt#L319-L330) the given perm for that player UUID against LuckPerms.

There is mutiple ways to achieve that; this one is just one top of my head. Would you be willing to make such a change ? If you don't have time but still like the idea, I can take a deeper look at it and maybe propose submit a PR

**Comment by fzzyhmstrs** [comment]
Great suggestion! Integrating LuckPerms (probably via `fabric-permissions-api`) would require a bit of a rethink, but definitely something I'll look into at some point

Rethink would be needed because vanilla permissions are available on the client, while LuckPerms are not, and other perm mods also may not be. Might have to do something like a permissions report as part of the sync packet so the screen manager can inspect it for required permissions.

The probable layout of the annotation will be `@WithCustomPerms(String[] args)`. It's certainly plausible that multiple permissions groups would have access to a setting.

**Comment by fzzyhmstrs** [comment]
This was implemented as of 0.4.x! Also integrates directly with Forge Permissions API on the (neo)forge versions
